config/routes.rb
Rails.application.routes.draw do
  get 'movies/all'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'list#index'
  resources :lists do
    resources :bookmarks, only: %i[index new create]
  end
  resources :bookmarks, only: :destroy
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def all
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<div class="container">
  <h1>Bookmarks</h1>
  <% @bookmarks.each do |bookmark| %>
    <ul>
      <li><%= bookmark.comment %></li>
    </ul>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  </head>

  <body>
    <%= yield %>
     <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container list_creator">
  <div class="header">
    <div class="list-card mt-5"> <%# ⬅️ MAIN CARD%>
     <h1>WatchList Creator</h1>
      <span class="lists-tag"><%= pluralize(@lists.size, 'list') %></span>
    </div>
  </div>
</div>
  <span class="mb-2"><small><em class="text-muted saved_lists"><%= "You haven't created any list yes!" if @lists.empty? %></em></small></span>
    <div class="mx-5 container list">
      <div class="lists_list">
        <div class="header-list d-flex align-items-center">
          <h2 class="my-3">Your Lists</h2>
            <%= link_to 'add list', new_list_path, :class => "ms-3 btn btn-flat rounded-pill"%>
        </div>
    <div class="list-grid">
      <% @lists.each do |list| %>
        <div class="list-item-card">
          <div class="banner-movie-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
            <strong><%= link_to list.name, list_path(list) %></strong> <%# ⬅️ LIST NAME%>
              <div class="d-flex align-items-end justify-content-between pt-4">
                <span><%= pluralize(list.movies.size, 'movie') %></span>
              </div>
        </div>
      <% end %>
    </div>
      </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%=link_to "/lists" do %>
  <i class="back_button mt-5 ms-5 btn btn-cancel rounded-pill">Go back to all lists</i>
<% end %>
  <div class="container-bookmark ml-5 mb-5 my-5 mx-5">
    <div class="card-category card-large">
      <div class="banner-movie-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
      <h1><%= @list.name %></h1>
        <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
          <div class="d-flex justify-content-between my-4">
            <div class="btns">
              <%= link_to 'add a movie', new_list_bookmark_path(@list), class: 'btn btn-flat' %>
              <%= link_to 'delete this list', list_path(@list), class: 'btn btn-cancel', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this list?' } %>
            </div>
          </div>
        </div>
      </div>
        <span class="mb-2"><small><em class="text-muted saved_movies"><%= "You haven't added any movies yet!" if @list.movies.empty? %></em></small></span>
      <div class="my-2">
        <div class="movie-grid">
          <% @list.movies.each do |movie| %>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
              <div class="movie-card" data-aos="zoom-in">
                <div class="bg-white rounded shadow h-100">
                  <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img rounded-top height: 400px' %>
                  <div class="p-3 rounded-bottom d-flex flex-column">
                    <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
                    <small class="text-muted"><%= movie.overview %></small>
                    <div class="d-flex align-items-end justify-content-between pt-4">
                      <div>
                        <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
                      </div>
                    <small class="text-right flex-shrink-0"><%= link_to 'delete', bookmark_path(bookmark), data: { turbo_method: 'delete', turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-light p-1 border rounded-pill bg-danger' %></small>
                    </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
      </div>
    </div>

app/views/movies/all.html.erb
<div class="container">
  <h1>Movies</h1>
  <% @movies.each do |movie| %>
    <li><%= movie.title %>, rating : <%= movie.rating %></li>
    <p><%= movie.overview %></p>
    <img src=<%= movie.poster_url %> class="movie-img">
    <% end %>
</div>